apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: microservices
spec:
  mode: daemonset # Specifies how to deploy the collector, cf https://github.com/open-telemetry/opentelemetry-operator/blob/main/README.md#deployment-modes
  image: otel/opentelemetry-collector-contrib:0.133.0
  config:
    receivers: # How to receive Open Telemetry data.
      otlp:
        protocols:
          grpc: {}
          http: {}

    exporters: # Where to export Open Telemetry data.
      otlp/signoz:
        endpoint: signoz-otel-collector.observability:4317
        tls:
          insecure: true
      loadbalancing: # Introducing the loadbalancer exporter that can route traces to the same collector based on a routing_key
        routing_key: "traceID"
        protocol:
          otlp:
            tls:
              insecure: true
        resolver:
          dns:
            hostname: otel-sampler-collector-headless

    service: # Configure each pipeline of Open Telemetry data.
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [otlp/signoz]
        traces:
          receivers: [otlp]
          exporters: [loadbalancing]
        metrics:
          receivers: [otlp]
          exporters: [otlp/signoz]
