name: Build Order Service

on:
  push:
    paths:
      - "microservices/order/**"
      - "!microservices/order/infra/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-build:
    name: Build Order service
    uses: ./.github/workflows/build-microservice.yml
    with:
      service-name: order
