name: Build Shopping Cart Service

on:
  push:
    paths:
      - "microservices/shopping-cart/**"
      - "!microservices/shopping-cart/infra/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-build:
    name: Build Shopping cart service
    uses: ./.github/workflows/build-microservice.yml
    with:
      service-name: shopping-cart
