name: Build Product Service

on:
  push:
    paths:
      - "microservices/product/**"
      - "!microservices/product/infra/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-build:
    name: Build Product service
    uses: ./.github/workflows/build-microservice.yml
    with:
      service-name: product
